/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BtCharts: typeof import('./../src/components/base/bt-charts/index.vue')['default']
    BtCloseBtn: typeof import('./../src/components/base/bt-close-btn/index.vue')['default']
    BtCode: typeof import('./../src/components/base/bt-code/index.vue')['default']
    BtConfigProvider: typeof import('./../src/components/ui/bt-config-provider/index.vue')['default']
    BtEditor: typeof import('./../src/components/base/bt-editor/index.vue')['default']
    BtFileUpload: typeof import('./../src/components/base/bt-file-upload/index.vue')['default']
    BtForm: typeof import('./../src/components/ui/bt-form/index.vue')['default']
    BtHelp: typeof import('./../src/components/base/bt-help/index.vue')['default']
    BtLogs: typeof import('./../src/components/base/bt-logs/index.vue')['default']
    BtModal: typeof import('./../src/components/ui/bt-modal/index.vue')['default']
    BtMore: typeof import('./../src/components/base/bt-more/index.vue')['default']
    BtPreview: typeof import('./../src/components/base/bt-preview/index.vue')['default']
    BtRouteTabs: typeof import('./../src/components/base/bt-route-tabs/index.vue')['default']
    BtSearch: typeof import('./../src/components/base/bt-search/index.vue')['default']
    BtTableBatch: typeof import('./../src/components/base/bt-table-batch/index.vue')['default']
    BtTableHelp: typeof import('./../src/components/base/bt-table-help/index.vue')['default']
    BtTableLayout: typeof import('./../src/components/base/bt-table-layout/index.vue')['default']
    BtTablePage: typeof import('./../src/components/ui/bt-table-page/index.vue')['default']
    BtTablePassword: typeof import('./../src/components/base/bt-table-password/index.vue')['default']
    BtTabs: typeof import('./../src/components/ui/bt-tabs/index.vue')['default']
    BtTime: typeof import('./../src/components/base/bt-time/index.vue')['default']
    BtTimeRange: typeof import('./../src/components/base/bt-time-range/index.vue')['default']
    BtTips: typeof import('./../src/components/base/bt-tips/index.vue')['default']
    Message: typeof import('./../src/components/utils/message/index.tsx')['default']
    MessageList: typeof import('./../src/components/utils/message/message-list.tsx')['default']
    Method: typeof import('./../src/components/utils/confirm/method.tsx')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadError: typeof import('./../src/components/base/bt-file-upload/UploadError.vue')['default']
    UploadProgress: typeof import('./../src/components/base/bt-file-upload/UploadProgress.vue')['default']
    UploadPrompt: typeof import('./../src/components/base/bt-file-upload/UploadPrompt.vue')['default']
    UploadSuccess: typeof import('./../src/components/base/bt-file-upload/UploadSuccess.vue')['default']
  }
}
